// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace HelloWorld {
  public static partial class GrpcLib
  {
    static readonly string __ServiceName = "HelloWorld.GrpcLib";

    static readonly grpc::Marshaller<global::HelloWorld.HelloRequest> __Marshaller_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::HelloWorld.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::HelloWorld.HelloReply> __Marshaller_HelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::HelloWorld.HelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply> __Method_SayHello = new grpc::Method<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_HelloRequest,
        __Marshaller_HelloReply);

    static readonly grpc::Method<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply> __Method_SayHelloAgain = new grpc::Method<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SayHelloAgain",
        __Marshaller_HelloRequest,
        __Marshaller_HelloReply);

    static readonly grpc::Method<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply> __Method_SayHelloThree = new grpc::Method<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SayHelloThree",
        __Marshaller_HelloRequest,
        __Marshaller_HelloReply);

    static readonly grpc::Method<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply> __Method_SayHelloFour = new grpc::Method<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SayHelloFour",
        __Marshaller_HelloRequest,
        __Marshaller_HelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::HelloWorld.HelloWorldReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GrpcLib</summary>
    public abstract partial class GrpcLibBase
    {
      public virtual global::System.Threading.Tasks.Task<global::HelloWorld.HelloReply> SayHello(global::HelloWorld.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SayHelloAgain(global::HelloWorld.HelloRequest request, grpc::IServerStreamWriter<global::HelloWorld.HelloReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::HelloWorld.HelloReply> SayHelloThree(grpc::IAsyncStreamReader<global::HelloWorld.HelloRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SayHelloFour(grpc::IAsyncStreamReader<global::HelloWorld.HelloRequest> requestStream, grpc::IServerStreamWriter<global::HelloWorld.HelloReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GrpcLib</summary>
    public partial class GrpcLibClient : grpc::ClientBase<GrpcLibClient>
    {
      /// <summary>Creates a new client for GrpcLib</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GrpcLibClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GrpcLib that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GrpcLibClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GrpcLibClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GrpcLibClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::HelloWorld.HelloReply SayHello(global::HelloWorld.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::HelloWorld.HelloReply SayHello(global::HelloWorld.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::HelloWorld.HelloReply> SayHelloAsync(global::HelloWorld.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::HelloWorld.HelloReply> SayHelloAsync(global::HelloWorld.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::HelloWorld.HelloReply> SayHelloAgain(global::HelloWorld.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloAgain(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::HelloWorld.HelloReply> SayHelloAgain(global::HelloWorld.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SayHelloAgain, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply> SayHelloThree(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloThree(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply> SayHelloThree(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SayHelloThree, null, options);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply> SayHelloFour(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloFour(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::HelloWorld.HelloRequest, global::HelloWorld.HelloReply> SayHelloFour(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SayHelloFour, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GrpcLibClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GrpcLibClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GrpcLibBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello)
          .AddMethod(__Method_SayHelloAgain, serviceImpl.SayHelloAgain)
          .AddMethod(__Method_SayHelloThree, serviceImpl.SayHelloThree)
          .AddMethod(__Method_SayHelloFour, serviceImpl.SayHelloFour).Build();
    }

  }
}
#endregion
